deployment:
  replicaCount: 3
  name: app-httpd-external
  image:
    name: httpd
    tag: latest
  annotations:
    deskripsi: "Belajar Helm basic 2"

service:
  name: svc-loadbalance
  type: LoadBalancer
  port: 80
  targetPort: 80