deployment:
  replicaCount: 1
  name: app-httpd-internal
  image:
    name: httpd
    tag: latest
  annotations:
    deskripsi: "Belajar Helm basic 2"

service:
  name: svc-nodeport
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32000